# 项目创建函数

#' Create a new R project with standard structure
#'
#' This function creates a new R project with a standardized directory structure
#' including common subdirectories, configuration files, and documentation.
#'
#' @param project_name Character string for the project name
#' @param path Character string for the project path (default: current working directory)
#' @param setup_env Logical, whether to set up environment (default: TRUE)
#' @return Invisible NULL
#' @export
#' @examples
#' \dontrun{
#' # Create project in current directory
#' create_r_project("my_analysis_project")
#'
#' # Create project in specific path
#' create_r_project("my_analysis_project", path = "~/projects")
#'
#' # Create without environment setup
#' create_r_project("my_analysis_project", setup_env = FALSE)
#' }
create_r_project <- function(project_name, path = getwd(), setup_env = TRUE) {
  # Parameter validation
  if (missing(project_name) || is.null(project_name)) {
    stop("Parameter 'project_name' is required and cannot be empty")
  }
  
  if (!is.character(project_name) || length(project_name) != 1) {
    stop("Parameter 'project_name' must be a character vector of length 1")
  }
  
  if (!is.character(path) || length(path) != 1) {
    stop("Parameter 'path' must be a character vector of length 1")
  }
  
  # 创建项目目录
  project_path <- file.path(path, project_name)
  
  if (dir.exists(project_path)) {
    stop("Project directory already exists: ", project_path)
  }
  
  # 创建主项目目录
  dir.create(project_path, recursive = TRUE, showWarnings = FALSE)
  
  # 创建标准子目录
  subdirs <- c("data", "R", "docs", "tests", "vignettes", "inst", "output", "figures", "reports")
  for (dir in subdirs) {
    dir.create(file.path(project_path, dir), recursive = TRUE, showWarnings = FALSE)
  }
  
  # Create .Rprofile file
  rprofile_content <- paste0(
    "# .Rprofile for ", project_name, "\n",
    "# Set project-specific options\n\n",
    "# Set working directory to project root\n",
    "setwd(dirname(rstudioapi::getSourceEditorContext()$path))\n\n",
    "# Load common packages\n",
    "if (interactive()) {\n",
    "  library(dplyr)\n",
    "  library(ggplot2)\n",
    "  library(readr)\n",
    "}\n\n",
    "# Set project options\n",
    "options(stringsAsFactors = FALSE)\n",
    "options(scipen = 999)\n"
  )
  
  # Create .Rprofile only if setup_env is TRUE
  if (setup_env) {
    writeLines(rprofile_content, file.path(project_path, ".Rprofile"))
  }
  
  # Create README.md
  readme_content <- paste0(
    "# ", project_name, "\n\n",
    "## Project Description\n",
    "Brief description of the project.\n\n",
    "## Directory Structure\n",
    "- `data/`: Raw and processed data files\n",
    "- `R/`: R scripts and functions\n",
    "- `docs/`: Documentation files\n",
    "- `output/`: Output files and results\n",
    "- `figures/`: Generated figures and plots\n",
    "- `reports/`: Reports and presentations\n\n",
    "## Usage\n",
    "Describe how to use this project.\n\n",
    "## Dependencies\n",
    "List required R packages and their versions.\n"
  )
  
  writeLines(readme_content, file.path(project_path, "README.md"))
  
  # Create .gitignore
  gitignore_content <- c(
    "# R specific files",
    ".Rhistory",
    ".RData",
    ".Ruserdata",
    "*.Rproj",
    "",
    "# Data files",
    "data/*.csv",
    "data/*.xlsx",
    "data/*.rds",
    "",
    "# Output files",
    "output/*.pdf",
    "output/*.png",
    "output/*.jpg",
    "",
    "# Temporary files",
    "*.tmp",
    "*.temp",
    "",
    "# OS specific files",
    ".DS_Store",
    "Thumbs.db"
  )
  
  writeLines(gitignore_content, file.path(project_path, ".gitignore"))
  
  # Create DESCRIPTION file
  description_content <- paste0(
    "Package: ", project_name, "\n",
    "Type: Package\n",
    "Title: ", project_name, " Package\n",
    "Version: 0.0.0.9000\n",
    "Authors@R: person(\"Your\", \"Name\", email = \"your.email@example.com\", role = c(\"aut\", \"cre\"))\n",
    "Description: Brief description of the ", project_name, " package.\n",
    "License: MIT + file LICENSE\n",
    "Encoding: UTF-8\n",
    "LazyData: true\n",
    "RoxygenNote: 7.2.3\n"
  )
  
  writeLines(description_content, file.path(project_path, "DESCRIPTION"))
  
  # Create NAMESPACE file
  namespace_content <- paste0(
    "# Generated by roxygen2: do not edit by hand\n\n",
    "# Export all functions\n",
    "# exportPattern(\"^[[:alpha:]]+\")\n"
  )
  
  writeLines(namespace_content, file.path(project_path, "NAMESPACE"))
  
  # Set up environment if requested
  if (setup_env) {
    # Create environment setup script
    env_script <- paste0(
      "# Environment setup for ", project_name, "\n",
      "# Run this script to install required packages\n\n",
      "required_packages <- c(\n",
      "  \"dplyr\",\n",
      "  \"ggplot2\",\n",
      "  \"readr\",\n",
      "  \"tidyr\",\n",
      "  \"knitr\",\n",
      "  \"rmarkdown\"\n",
      ")\n\n",
      "# Install missing packages\n",
      "install_if_missing(required_packages)\n\n",
      "# Load packages\n",
      "load_packages(required_packages)\n\n",
      "cat(\"Environment setup completed!\\n\")\n"
    )
    
    writeLines(env_script, file.path(project_path, "setup_environment.R"))
  }
  
  cat("R project '", project_name, "' created successfully at:\n", project_path, "\n")
  cat("Standard directory structure has been created.\n")
  
  if (setup_env) {
    cat("Environment setup script 'setup_environment.R' has been created.\n")
  }
  
  invisible(NULL)
} 